name: Test, Compute SHA, and Release

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  VCPKG_PORT_NAME: falcon-database
  VCPKG_PORT_PATH: ports/falcon-database
  VCPKG_JSON: ports/falcon-database/vcpkg.json
  PORTFILE: ports/falcon-database/portfile.cmake

jobs:
  test-and-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake build-essential mono-complete docker-compose jq

      - name: Run tests (with Docker)
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_FEED: ${{ secrets.NUGET_FEED_URL }}
        run: make test-with-docker
